language: go

go:
  - 1.6.3
  - 1.7.3

env:
  global:
    - LIBGIT2_VERSION=0.24.3
    - PKG_CONFIG_PATH=/tmp/libgit2/lib/pkgconfig

# Compile libgit2
before_install: ./install-libgit2.sh

install: go get -d -v ./...
script: go install ./...
